# Generated by Django 4.2.6 on 2024-03-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
